# 数据文件路径配置
data_files:
  # 原始数据文件
  joint_angle_raw: 'data/test_joint_angles.csv'       # 原始关节角度文件
  laser_pos_raw: 'data/test_positions.csv'           # 原始激光位置文件
  
  # 参数文件  
  dh_params: 'data/dh.csv'                      # DH参数文件
  joint_limits: 'data/joint_limits.csv'         # 关节限位文件
  
  # 手眼标定初始值
  calibration_results: 'data/hand_eye_calibration.csv'  # 校准结果文件

# 智能数据输入配置
data_input:
  # 支持的文件格式
  supported_formats: ["txt", "csv", "xlsx", "xls"]
  
  # 关节角度数据配置
  joint_angles:
    # 字段识别模式（按优先级排序）
    field_patterns:
      - ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
      - ["J1", "J2", "J3", "J4", "J5", "J6"] 
      - ["axis1", "axis2", "axis3", "axis4", "axis5", "axis6"]
    unit: "degree"
    
    # Rokae格式兼容配置（CSV和TXT通用）
    rokae_format:
      pattern: 'j:\s*{\s*([^}]*?)\s*}'
      extract_count: 6
      
  # 位置数据配置
  positions:
    # 位置字段模式
    position_patterns: ["X", "Y", "Z", "pos_x", "pos_y", "pos_z"]
    # 姿态字段模式  
    orientation_patterns: ["Rx", "Ry", "Rz", "roll", "pitch", "yaw"]
    position_unit: "mm"
    orientation_unit: "degree"
    
    # 激光跟踪仪兼容配置
    laser_tracker:
      measurement_columns: [7, 8, 9, 10, 11, 12]  # 测量列索引
      nominal_columns: [1, 2, 3, 4, 5, 6]         # 标称列索引

# 机器人配置参数
robot_config:

  error_weights: [1.0, 1.0, 1.0, 0.01, 0.01, 0.01]
 
  fixed_indices: []

# 优化配置
optimization:
  # Levenberg-Marquardt 优化参数
  lm_optimization:
    # 交替优化设置
    alternate_optimization:
      max_alt_iterations: 4             # 交替优化最大循环次数
      convergence_tol: 1e-4             # 交替优化收敛阈值
      max_sub_iterations_group1: 10    # 第一组参数子优化最大迭代次数
      max_sub_iterations_group2: 10     # 第二组参数子优化最大迭代次数
    
    # 阻尼参数设置
    damping:
      lambda_init_group1: 2.0           # 第一组参数初始阻尼因子
      lambda_init_group2: 0.001         # 第二组参数初始阻尼因子
      lambda_max: 1e8                   # 最大阻尼因子阈值
      lambda_min: 1e-7                  # 最小阻尼因子阈值
      damping_type: "marquardt"         # 阻尼类型: "marquardt" 或 "levenberg"
    
    # 参数约束
    constraints:
      max_theta_change_degrees: 1.0     # theta参数单步最大变化量(度)
      enable_quaternion_normalization: true  # 是否启用四元数归一化
    
    # 输出设置
    output:
      save_delta_values: true           # 是否保存delta值到CSV
      delta_csv_file: "results/delta_values.csv"  # delta值保存文件路径
      save_optimization_results: true   # 是否保存优化结果
      results_prefix: "results/optimized"  # 结果文件前缀 